server {
    listen 80;

    location = /health {
        proxy_pass http://api:8000;
    }

    location /chatwoot/webhook {
        proxy_pass http://api:8000;
    }

    location / {
        proxy_pass http://chatwoot_rails:3000;
    }
}
